#define STATUS_ITEM_VIEW_WIDTH 70.0

#define POPUP_HEIGHT 600
#define PANEL_WIDTH 400

#define OPEN_DURATION .2
#define CLOSE_DURATION .1

#define BUTTON_SIZE 45.0

#define TRIANGLE_WIDTH 20
#define TRIANGLE_HEIGHT 10

#define CORNER_RADIUS 8.0f
#define FILL_OPACITY 100.0f